Repository WildCodeSchool-2023-09/JS-RMT-React_If-Projet2-Watch_now, pull requests merged in 2023-11, with the labels that each got.

#6 Feat comp movies
  backend/database/schema.sql
  backend/package.json
  backend/src/controllers/movieControllers.js
  backend/src/models/ItemManager.js
  backend/src/router.js
  frontend/.eslintrc.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/assets/logo-white.svg
  frontend/src/assets/logo.svg
  frontend/src/assets/search.svg
  frontend/src/components/Counter.jsx
  frontend/src/components/ListMovies.jsx
  frontend/src/main.jsx
  frontend/src/pages/AllMovies.jsx
  frontend/src/pages/AllProduct.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/MoviePage.jsx
  frontend/src/pages/OneProduct.jsx
  frontend/src/style/AllMovies.css
  frontend/src/style/Home.css
  frontend/src/style/ListMovies.css
  frontend/src/style/NavBar.css
Labels: Review Formateur

#7 Feat navbar new
  backend/src/router.js
  frontend/src/App.jsx
  frontend/src/components/NavBar.jsx
  frontend/src/components/NavbarModal.jsx
  frontend/src/main.jsx
  frontend/src/style/NavBar.css
  frontend/src/style/NavbarModal.css
Labels: Review Formateur

#2 Feat displayby
  frontend/package-lock.json
  frontend/package.json
  frontend/src/Index.css
  frontend/src/main.jsx
  frontend/src/pages/MoviePage.jsx
  frontend/src/style/Circular.css
  frontend/src/style/MoviePage.css
Labels: Review Formateur

#8 Correction responsive 3 screens + id --> className listMovie
  frontend/src/components/ListMovies.jsx
  frontend/src/style/ListMovies.css
Labels: Review Formateur

#10 Feat comp movies
  frontend/src/components/ListMovies.jsx
  frontend/src/style/ListMovies.css
Labels: Review Team, Review Formateur

#12 Feat movie filters
  backend/src/router.js
  frontend/src/Index.css
  frontend/src/components/Filters.jsx
  frontend/src/main.jsx
  frontend/src/pages/AllMovies.jsx
  frontend/src/style/Filters.css
Labels: Review Team, Review Formateur

#9 Feat contact
  frontend/package-lock.json
  frontend/package.json
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/components/Contact.css
  frontend/src/components/Contact.jsx
Labels: Changed Asked

#18 Changement nom onglet + favicon logo
  frontend/index.html
  frontend/src/assets/favicon.svg
Labels: Review Formateur

#17 Feat widget movie
  frontend/src/App.css
  frontend/src/components/WidgetMoviesBest.jsx
  frontend/src/components/WidgetMoviesRecent.jsx
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
  frontend/src/style/WidgetMoviesBest.css
  frontend/src/style/WidgetMoviesRecent.css
Labels: Review Formateur

#14 Css global --> Index.css
  frontend/src/Index.css
  frontend/src/pages/Home.jsx
  frontend/src/style/Home.css
Labels: Review Formateur

#15 Feat navbar
  frontend/src/index.css
  frontend/src/pages/AllMovies.jsx
  frontend/src/pages/MyList.jsx
  frontend/src/style/NavBar.css
Labels: Review Formateur

#16 Ajout footer + css
  frontend/src/App.jsx
  frontend/src/Index.css
  frontend/src/assets/logo-white-name.svg
  frontend/src/components/Footer.jsx
  frontend/src/main.jsx
  frontend/src/pages/Home.jsx
  frontend/src/style/Footer.css
Labels: Review Formateur

#22 Final Fix
  frontend/src/App.css
  frontend/src/App.jsx
  frontend/src/Index.css
  frontend/src/components/Contact.jsx
  frontend/src/pages/AllMovies.jsx
  frontend/src/pages/Home.jsx
  frontend/src/pages/MoviePage.jsx
  frontend/src/style/Contact.css
  frontend/src/style/MoviePage.css
  frontend/src/style/WidgetMoviesBest.css
Labels: Review Formateur
